### ISSUE TITLE
'BugfenderSDK/BugfenderSDK.h' file not found

### ISSUE THREAD

**Issue by niuwenbo** [bugfender/cordova-plugin-bugfender#5]
i used the ionic 4 and capacitor build the project. i got the error in Xcode10.
can anyone tell me how to fixed this issue

Thanks

**Comment by jgimenez** [comment]
This probably happens when the cordova-plugin-bugfender is not installed. Maybe try to follow the installation instructions again, especially be careful with:

* Setting the minimum target SDK
* Install CocoaPods
* Check any error messages that might appear during the installation (to do that, remove the plugin and add it again)
* If that doesn't work, rebuild the platform (remove the ios platform and add it again)

If you need any further assistance please contact our Support, maybe we can help you better if we see more details.

**Comment by niuwenbo** [comment]
@jgimenez thanks for your reply
i used 'npx cap sync' add the plugins to the ios project, i also can see the the plugin in Xcode10
![image](https://user-images.githubusercontent.com/5061472/48196193-c384ff80-e38c-11e8-85f2-db88f98e8e61.png)

**Comment by john-yick** [comment]
@jgimenez We are also seeing the same issue. We have installed the fix for the xcode 10 using CocoaPods. It seems that the project is either missing a reference or a linked file?

Any help would be appreciated.

**Comment by jgimenez** [comment]
Hi @john-yick if you have already tried the bullet list I posted earlier, maybe you can contact our support team to check with you on a 1-on-1 basis
