### ISSUE TITLE
Bugfender manual logging failing silently

### ISSUE THREAD

**Issue by ayoshimiya** [bugfender/cordova-plugin-bugfender#6]
Hi, I'm trying to use the plugin on a cordova project (we are working with only android for the moment), and found out the manual logs were not being sent to the server. Upon a closer look I noticed that in https://github.com/bugfender/cordova-plugin-bugfender/blob/master/www/bugfender.js#L101 The call to cordova was throwing a JSON Error.

I don't quite understand the usage of the code above that line, it creates a `new Error` and then it parses it and the values returned on the capturing of the match (seems wrong) are used to be sent as line, func and file, seems like a default values settings, or maybe webview engine changed at some point the way it returns the stack, or the regex above is wrong. I also checked the git history and it seems that some functionality was removed there.

I commented that part out and set some defaults for those lines and the rest seems to work just fine. I also noticed that `line` should be a number (can't be blank) and message must be a string (if you send an object algonside the message then it would cause JSON Error as well) I casted it to string and it seems that that's enough.

For the moment I am able to send those messages and see them correctly on the web dashboard. But I thought I would let you know of this issue.

Regards

**Comment by jgimenez** [comment]
Hi @ayoshimiya , thanks for letting us know. The code using the `new Error` finds the function name, file name and line number of the caller function, so that you can see it in Bugfender. It's safe to pass empty values as you're doing, but of course this removes some functionality that might be interesting. Most likely, the problem is related to something browser-specific. Do you know in which platform and version is this happening? Thanks

**Comment by jgimenez** [comment]
Thanks for reporting this, we issued an update of the SDK, version 1.2.1, fixing this problem
